server:
  port: 8081
  servlet:
    context-path: /renewen
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  main:
    web-application-type: servlet
    banner-mode: 'off'
#  profiles:
#    active: local    


# 네이버 로그인 연동
#  security:
#    oauth2:
#     client:
#      registration:
#        google:
#          client-id: 780755290259-30bopb1kcelc9laqk5ijln2evlplg9qb.apps.googleusercontent.com
#          client-secret: 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
#          scope: 


  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/renewen?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
mybatis:
  mapper-locations: classpath:mapper/*.xml 
  type-aliases-package: kr.smhrd.renewen.model  
  configuration:
    map-underscore-to-camel-case: true  

    
    
    