server:
  port: 8081
  servlet:
    context-path: /renewen
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    web-application-type: servlet
    banner-mode: 'off'
<<<<<<< HEAD
#  profiles:
#    active: local    


# 네이버 로그인 연동
#  security:
#    oauth2:
#     client:
#      registration:
#        google:
#          client-id: 780755290259-30bopb1kcelc9laqk5ijln2evlplg9qb.apps.googleusercontent.com
#          client-secret: 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
#          scope: 


=======
>>>>>>> branch 'main' of https://github.com/2023-SMHRD-KDT-IOT-4/renewen
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/renewen?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
mybatis:
  mapper-locations: classpath:mapper/*.xml 
  type-aliases-package: kr.smhrd.renewen.model  
  configuration:
<<<<<<< HEAD
    map-underscore-to-camel-case: true  

    
=======
    map-underscore-to-camel-case: true    
    
# 별도 설정
upload:
  path: C:\\upload
  img: \\imgs
>>>>>>> branch 'main' of https://github.com/2023-SMHRD-KDT-IOT-4/renewen
    
    