server:
  port: 8081
  servlet:
    context-path: /renewen
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  jackson:
    time-zone: Asia/Seoul
  servlet: 
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    web-application-type: servlet
    banner-mode: 'off'
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/renewen?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
mybatis:
  mapper-locations: classpath:mapper/*.xml 
  type-aliases-package: kr.smhrd.renewen.model  
  configuration:
    map-underscore-to-camel-case: true    
    
     
    
# ====================================================================================================================    

# 별도 설정
upload:
  path: C:\\upload
  img: \\imgs   
url:
  flask: http://127.0.0.1:8083/
api:
  hub-key: CXKwvqlxTqCysL6pcS6glQ  